#!/bin/bash

# delete Zocalo.db file if exist
if [ -f Zocalo.db ]
then
    rm Zocalo.db
    echo 'Removed Zocalo.db' 
fi

# setup database schema
python3 database_setup.py
echo 'Created Zocalo schema'

# create lookup table data
python3 lookup_data.py
echo 'Created Zocalo lookup data'

# testing data
python3 create_tmp_data.py
echo 'Created Zocalo testing data'
